POST http://localhost:3000/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3000/events/770f14b4-73c8-49c8-ba11-e17f861aa2f8/attendees
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@email.com"
}

###

GET http://localhost:3000/events/15203923-9df9-456b-82cf-104dd485214d

###

GET http://localhost:3000/attendees/1/badge